#ifndef ICEPANIC_AMIGA_ASSETS_H
#define ICEPANIC_AMIGA_ASSETS_H

#include <stdint.h>

#define AMIGA_ASSET_DEPTH 5
#define AMIGA_ASSET_PALETTE_COUNT 32
#define AMIGA_ASSET_TILE_SIZE 16
#define AMIGA_ASSET_ROW_WORDS_TILE 1
#define AMIGA_ASSET_ROW_BYTES_TILE 2
#define AMIGA_ASSET_ROW_WORDS_WIDE 2
#define AMIGA_ASSET_ROW_BYTES_WIDE 4
#define AMIGA_ASSET_TILE_BYTES 160
#define AMIGA_ASSET_TILE_MASK_BYTES 160
#define AMIGA_ASSET_PLANE_BYTES 64
#define AMIGA_ASSET_BOB_BYTES 320
#define AMIGA_ASSET_MASK_BYTES 320
#define AMIGA_ASSET_SPRITE_COUNT 41
#define AMIGA_TITLE_OVERLAY_WIDTH 125
#define AMIGA_TITLE_OVERLAY_HEIGHT 83
#define AMIGA_TITLE_OVERLAY_ANCHOR_X 0
#define AMIGA_TITLE_OVERLAY_ANCHOR_Y 0
#define AMIGA_TITLE_OVERLAY_TRANSPARENT_INDEX 255
#define AMIGA_TITLE_OVERLAY_ROW_WORDS 9
#define AMIGA_TITLE_OVERLAY_ROW_BYTES 18
#define AMIGA_TITLE_OVERLAY_BYTES 7470
#define AMIGA_TITLE_OVERLAY_MASK_BYTES 7470

typedef enum AmigaSpriteId {
    AMIGA_SPR_FLOOR = 0,
    AMIGA_SPR_WALL = 1,
    AMIGA_SPR_BORDER = 2,
    AMIGA_SPR_BLOCK_ICE = 3,
    AMIGA_SPR_BLOCK_SPECIAL = 4,
    AMIGA_SPR_BLOCK_CRACKED = 5,
    AMIGA_SPR_BLOCK_UNBREAKABLE = 6,
    AMIGA_SPR_PLAYER_UP = 7,
    AMIGA_SPR_PLAYER_UP_ALT = 8,
    AMIGA_SPR_PLAYER_DOWN = 9,
    AMIGA_SPR_PLAYER_DOWN_ALT = 10,
    AMIGA_SPR_PLAYER_LEFT = 11,
    AMIGA_SPR_PLAYER_LEFT_ALT = 12,
    AMIGA_SPR_PLAYER_RIGHT = 13,
    AMIGA_SPR_PLAYER_RIGHT_ALT = 14,
    AMIGA_SPR_ENEMY_A = 15,
    AMIGA_SPR_ENEMY_A_ALT = 16,
    AMIGA_SPR_ENEMY_B = 17,
    AMIGA_SPR_ENEMY_B_ALT = 18,
    AMIGA_SPR_ENEMY_A_DEATH_0 = 19,
    AMIGA_SPR_ENEMY_A_DEATH_1 = 20,
    AMIGA_SPR_ENEMY_B_DEATH_0 = 21,
    AMIGA_SPR_ENEMY_B_DEATH_1 = 22,
    AMIGA_SPR_ITEM_FISH = 23,
    AMIGA_SPR_ITEM_EGG = 24,
    AMIGA_SPR_ITEM_GEM = 25,
    AMIGA_SPR_ITEM_FRUIT = 26,
    AMIGA_SPR_ITEM_MYSTERY = 27,
    AMIGA_SPR_HUD_LIFE = 28,
    AMIGA_SPR_EFFECT_SPARK = 29,
    AMIGA_SPR_MINE_0 = 30,
    AMIGA_SPR_MINE_1 = 31,
    AMIGA_SPR_MINE_2 = 32,
    AMIGA_SPR_ENEMY_C = 33,
    AMIGA_SPR_ENEMY_C_ALT = 34,
    AMIGA_SPR_ENEMY_C_DEATH_0 = 35,
    AMIGA_SPR_ENEMY_C_DEATH_1 = 36,
    AMIGA_SPR_ENEMY_D = 37,
    AMIGA_SPR_ENEMY_D_ALT = 38,
    AMIGA_SPR_ENEMY_D_DEATH_0 = 39,
    AMIGA_SPR_ENEMY_D_DEATH_1 = 40,
    AMIGA_SPR_COUNT = 41
} AmigaSpriteId;

extern const uint16_t g_amiga_palette[AMIGA_ASSET_PALETTE_COUNT];
extern const uint8_t g_amiga_tile_data[AMIGA_ASSET_SPRITE_COUNT][AMIGA_ASSET_TILE_BYTES];
extern const uint8_t g_amiga_tile_mask[AMIGA_ASSET_SPRITE_COUNT][AMIGA_ASSET_TILE_MASK_BYTES];
extern const uint8_t g_amiga_bob_data[AMIGA_ASSET_SPRITE_COUNT][AMIGA_ASSET_BOB_BYTES];
extern const uint8_t g_amiga_bob_mask[AMIGA_ASSET_SPRITE_COUNT][AMIGA_ASSET_MASK_BYTES];
extern const uint8_t g_amiga_title_overlay_data[AMIGA_TITLE_OVERLAY_BYTES];
extern const uint8_t g_amiga_title_overlay_mask[AMIGA_TITLE_OVERLAY_MASK_BYTES];

#endif
