#ifndef ICEPANIC_AMIGA_SFX_ASSETS_H
#define ICEPANIC_AMIGA_SFX_ASSETS_H

#include <exec/types.h>

#define AMIGA_SFX_SAMPLE_RATE 8000
#define AMIGA_SFX_SAMPLE_PERIOD 443
#define AMIGA_SFX_DATA_BYTES 42560UL

typedef enum AmigaSfxSampleId {
    AMIGA_SFX_SAMPLE_NONE = 0,
    AMIGA_SFX_SAMPLE_SLOT_CHIME = 1,
    AMIGA_SFX_SAMPLE_REWARD_JINGLE = 2,
    AMIGA_SFX_SAMPLE_LEVEL_UP_FANFARE = 3,
    AMIGA_SFX_SAMPLE_DEATH_JINGLE = 4,
    AMIGA_SFX_SAMPLE_GAME_OVER_JINGLE = 5,
    AMIGA_SFX_SAMPLE_LIFE_LOSS_FANFARE = 6,
    AMIGA_SFX_SAMPLE_COMBO_JINGLE = 7,
    AMIGA_SFX_SAMPLE_BLOCK_PUSH_SWISH = 8,
    AMIGA_SFX_SAMPLE_TITLE_START_JINGLE = 9,
    AMIGA_SFX_SAMPLE_TITLE_CONFIRM_CHIRP = 10,
    AMIGA_SFX_SAMPLE_NEW_HIGH_SCORE_FANFARE = 11,
    AMIGA_SFX_SAMPLE_CRUSH = 12,
    AMIGA_SFX_SAMPLE_TIMER_DANGER = 13,
    AMIGA_SFX_SAMPLE_ROUND_START = 14,
    AMIGA_SFX_SAMPLE_MINE_PLACED = 15,
    AMIGA_SFX_SAMPLE_MINE_EXPLODED = 16,
    AMIGA_SFX_SAMPLE_BLOCK_IMPACT = 17,
    AMIGA_SFX_SAMPLE_META_SPENT = 18,
    AMIGA_SFX_SAMPLE_STAGE_MODIFIER = 19,
    AMIGA_SFX_SAMPLE_COUNT
} AmigaSfxSampleId;

extern const UBYTE g_amiga_sfx_data[AMIGA_SFX_DATA_BYTES];
extern const ULONG g_amiga_sfx_offsets[AMIGA_SFX_SAMPLE_COUNT];
extern const UWORD g_amiga_sfx_lengths_words[AMIGA_SFX_SAMPLE_COUNT];
extern const UBYTE g_amiga_sfx_ticks[AMIGA_SFX_SAMPLE_COUNT];

#endif
