#ifndef ICEPANIC_AMIGA_ASSETS_OCS_H
#define ICEPANIC_AMIGA_ASSETS_OCS_H

#include "amiga_assets.h"

#define AMIGA_OCS_GFX_MASK_OFFSET 0UL
#define AMIGA_OCS_GFX_BOB_OFFSET (AMIGA_OCS_GFX_MASK_OFFSET + ((unsigned long)AMIGA_ASSET_SPRITE_COUNT * AMIGA_ASSET_MASK_BYTES))
#define AMIGA_OCS_GFX_TILE_MASK_OFFSET (AMIGA_OCS_GFX_BOB_OFFSET + ((unsigned long)AMIGA_ASSET_SPRITE_COUNT * AMIGA_ASSET_BOB_BYTES))
#define AMIGA_OCS_GFX_TILE_OFFSET (AMIGA_OCS_GFX_TILE_MASK_OFFSET + ((unsigned long)AMIGA_ASSET_SPRITE_COUNT * AMIGA_ASSET_TILE_MASK_BYTES))
#define AMIGA_OCS_GFX_TITLE_OFFSET (AMIGA_OCS_GFX_TILE_OFFSET + ((unsigned long)AMIGA_ASSET_SPRITE_COUNT * AMIGA_ASSET_TILE_BYTES))
#define AMIGA_OCS_GFX_TITLE_MASK_OFFSET (AMIGA_OCS_GFX_TITLE_OFFSET + AMIGA_TITLE_OVERLAY_BYTES)
#define AMIGA_OCS_GFX_BYTES (AMIGA_OCS_GFX_TITLE_MASK_OFFSET + AMIGA_TITLE_OVERLAY_MASK_BYTES)

#endif
